#!/bin/bash

rsync -v -r ~/git/finalYearProject/bash \
            ~/git/finalYearProject/code \
            ~/git/finalYearProject/exe \
            ~/git/finalYearProject/graphs \
            ~/git/finalYearProject/python \
            cillian@hclserver2a40.ucd.ie:/home/cillian/project/
             